[build]
    functions = "functions/"
    command = "npm run build"
    publish = "public/"
[build.environment]
    NODE_ENV = "production"
[[headers]]
    for = "/Hitchcock.woff2"
    [headers.values]
        Access-Control-Allow-Origin = "*"